:default: &default
  adapter: postgresql
  encoding: unicode
  username: vscode
  password: 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lumensec_api_development

test:
  <<: *default
  database: lumensec_api_test

production:
  <<: *default
  database: lumensec_api_production
